RKC_IS/RKC_IS/Areas/Admin/Controllers/ROLEsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using RKC_IS.DataAccess.Model.AutoMapping;

namespace RKC_IS.Areas.Admin.Controllers
{
    [Authorize(Roles = "admin")]
    public class ROLEsController : Controller
    {
        private ConnectionMap_RKC_Database db = new ConnectionMap_RKC_Database();

        // GET: Admin/ROLEs
        public ActionResult Index()
        {
            var rOLE = db.ROLE.Include(r => r.SY_STAV);
            return View(rOLE.ToList());
        }

        // GET: Admin/ROLEs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ROLE rOLE = db.ROLE.Find(id);
            if (rOLE == null)
            {
                return HttpNotFound();
            }
            return View(rOLE);
        }

        // GET: Admin/ROLEs/Create
        public ActionResult Create()
        {
            //ViewBag.STAV = new SelectList(db.SY_STAV, "ID", "TABULKA");
            //ViewBag.STAV = new SelectList(db.SY_STAV, "ID", "TABULKA");
            ViewBag.STAV = new SelectList(db.SY_STAV.Where(o => o.TABULKA == "ROLE").Where(o => o.STAV == 1), "ID", "POPIS");
            return View();
        }

        // POST: Admin/ROLEs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,STAV,ZKRATKA,POPIS_ROLE,STAV_NASLEDUJICI,C_USER,C_DATE,M_USER,M_DATE")] ROLE rOLE)
        {
            rOLE.C_USER = User.Identity.GetUserId<int>();
            rOLE.C_DATE = DateTime.Now;

            if (ModelState.IsValid)
            {
                db.ROLE.Add(rOLE);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            //ViewBag.STAV = new SelectList(db.SY_STAV, "ID", "TABULKA", rOLE.STAV);
            ViewBag.STAV = new SelectList(db.SY_STAV, "ID", "POPIS", rOLE.STAV);
            return View(rOLE);
        }

        // GET: Admin/ROLEs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ROLE rOLE = db.ROLE.Find(id);
            if (rOLE == null)
            {
                return HttpNotFound();
            }
            ViewBag.STAV = new SelectList(db.SY_STAV, "ID", "TABULKA", rOLE.STAV);
            ViewBag.STAV = new SelectList(db.SY_STAV, "ID", "TABULKA", rOLE.STAV);
            return View(rOLE);
        }

        // POST: Admin/ROLEs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,STAV,ZKRATKA,POPIS_ROLE,STAV_NASLEDUJICI,C_USER,C_DATE,M_USER,M_DATE")] ROLE rOLE)
        {
            if (ModelState.IsValid)
            {
                db.Entry(rOLE).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.STAV = new SelectList(db.SY_STAV, "ID", "TABULKA", rOLE.STAV);
            ViewBag.STAV = new SelectList(db.SY_STAV, "ID", "TABULKA", rOLE.STAV);
            return View(rOLE);
        }

        // GET: Admin/ROLEs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ROLE rOLE = db.ROLE.Find(id);
            if (rOLE == null)
            {
                return HttpNotFound();
            }
            return View(rOLE);
        }

        // POST: Admin/ROLEs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ROLE rOLE = db.ROLE.Find(id);
            db.ROLE.Remove(rOLE);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RKC_IS/RKC_IS/Areas/Admin/Controllers/SY_STAVController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RKC_IS.DataAccess.Model.AutoMapping;

namespace RKC_IS.Areas.Admin.Controllers
{
    public class SY_STAVController : Controller
    {
        private ConnectionMap_RKC_Database db = new ConnectionMap_RKC_Database();

        // GET: Admin/SY_STAV
        public async Task<ActionResult> Index()
        {
            return View(await db.SY_STAV.ToListAsync());
        }

        // GET: Admin/SY_STAV/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SY_STAV sY_STAV = await db.SY_STAV.FindAsync(id);
            if (sY_STAV == null)
            {
                return HttpNotFound();
            }
            return View(sY_STAV);
        }

        // GET: Admin/SY_STAV/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/SY_STAV/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ID,TABULKA,STAV,POPIS,L_PLATI,BARVA")] SY_STAV sY_STAV)
        {
            if (ModelState.IsValid)
            {
                db.SY_STAV.Add(sY_STAV);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(sY_STAV);
        }

        // GET: Admin/SY_STAV/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SY_STAV sY_STAV = await db.SY_STAV.FindAsync(id);
            if (sY_STAV == null)
            {
                return HttpNotFound();
            }
            return View(sY_STAV);
        }

        // POST: Admin/SY_STAV/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ID,TABULKA,STAV,POPIS,L_PLATI,BARVA")] SY_STAV sY_STAV)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sY_STAV).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(sY_STAV);
        }

        // GET: Admin/SY_STAV/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SY_STAV sY_STAV = await db.SY_STAV.FindAsync(id);
            if (sY_STAV == null)
            {
                return HttpNotFound();
            }
            return View(sY_STAV);
        }

        // POST: Admin/SY_STAV/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            SY_STAV sY_STAV = await db.SY_STAV.FindAsync(id);
            db.SY_STAV.Remove(sY_STAV);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RKC_IS/RKC_IS/Areas/Admin/Controllers/UZIVATELController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RKC_IS.DataAccess.Model.AutoMapping;
using PagedList;

namespace RKC_IS.Areas.Admin.Controllers
{
    public class UZIVATELController : Controller
    {
        private ConnectionMap_RKC_Database db = new ConnectionMap_RKC_Database();

        // GET: Admin/UZIVATEL
        //public ActionResult Index()
        //{
        //    var uSER = db.USER.Include(u => u.SY_STAV);
        //    return View(uSER.ToList());
        //}


        //------přidáno-----------------
        public ActionResult Index(string sortOrder, string currentFilter, string searchStringJmeno, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "jmeno_desc" : "";
            ViewBag.DateSortParm = sortOrder == "prijmeni" ? "prijmeni_desc" : "prijmeni";

            if (searchStringJmeno != null)
            {
                page = 1;
            }
            else
            {
                searchStringJmeno = currentFilter;
            }

            ViewBag.CurrentFilter = searchStringJmeno;

            var uzivatel_data = from s in db.USER.Include(u => u.SY_STAV)
                                select s;
            if (!String.IsNullOrEmpty(searchStringJmeno))
            {
                uzivatel_data = uzivatel_data.Where(s => s.Jmeno.Contains(searchStringJmeno)
                                       || s.Prijmeni.Contains(searchStringJmeno));
            }
            switch (sortOrder)
            {
                case "jmeno_desc":
                    uzivatel_data = uzivatel_data.OrderByDescending(s => s.Jmeno);
                    break;
                case "prijmeni":
                    uzivatel_data = uzivatel_data.OrderBy(s => s.Prijmeni);
                    break;
                case "prijmeni_desc":
                    uzivatel_data = uzivatel_data.OrderByDescending(s => s.Prijmeni);
                    break;
                default:
                    uzivatel_data = uzivatel_data.OrderBy(s => s.Jmeno);
                    break;
            }
            int pageSize = 20;
            int pageNumber = (page ?? 1);

            if (Request.IsAjaxRequest())
            {
                return PartialView(uzivatel_data.ToPagedList(pageNumber, pageSize));
            }

            return View(uzivatel_data.ToPagedList(pageNumber, pageSize));
        }

        public string CiselnikPopis(string _kod)
        {
            string promennna = "";

            IList<CISELNIK_DATA> kodQuery = db.CISELNIK_DATA.Where(t => t.KOD == _kod).ToList();
            foreach (CISELNIK_DATA item in kodQuery)
            {
                promennna = item.POPIS;
            }

            return promennna;
        }

        // GET: Admin/UZIVATEL/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            USER uSER = db.USER.Find(id);
            if (uSER == null)
            {
                return HttpNotFound();
            }
            return View(uSER);
        }

        // GET: Admin/UZIVATEL/Create
        public ActionResult Create()
        {
            ViewBag.STAV = new SelectList(db.SY_STAV, "ID", "TABULKA");
            return View();
        }

        // POST: Admin/UZIVATEL/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,ZAOR_organizace,Jmeno,Prijmeni,OsobniCislo,PhoneNumber,Obec,Ulice,CisloDomu,PSC,DatumNastup,PlatovaTrida,Smena,CasPrihlaseni,C_USER,M_USER,C_DATE,M_DATE,UserName,PasswordHash,Email,STAV,STAV_NASLEDUJICI,EmailConfirmed,SecurityStamp,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,IsConfirmed,PasswordQuestion,PasswordAnswer,ActivationToken")] USER uSER)
        {
            if (ModelState.IsValid)
            {
                db.USER.Add(uSER);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.STAV = new SelectList(db.SY_STAV, "ID", "TABULKA", uSER.STAV);
            return View(uSER);
        }

        // GET: Admin/UZIVATEL/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            USER uSER = db.USER.Find(id);
            if (uSER == null)
            {
                return HttpNotFound();
            }
            ViewBag.STAV = new SelectList(db.SY_STAV, "ID", "TABULKA", uSER.STAV);
            return View(uSER);
        }

        // POST: Admin/UZIVATEL/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,ZAOR_organizace,Jmeno,Prijmeni,OsobniCislo,PhoneNumber,Obec,Ulice,CisloDomu,PSC,DatumNastup,PlatovaTrida,Smena,CasPrihlaseni,C_USER,M_USER,C_DATE,M_DATE,UserName,PasswordHash,Email,STAV,STAV_NASLEDUJICI,EmailConfirmed,SecurityStamp,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,IsConfirmed,PasswordQuestion,PasswordAnswer,ActivationToken")] USER uSER)
        {
            if (ModelState.IsValid)
            {
                db.Entry(uSER).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.STAV = new SelectList(db.SY_STAV, "ID", "TABULKA", uSER.STAV);
            return View(uSER);
        }

        // GET: Admin/UZIVATEL/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            USER uSER = db.USER.Find(id);
            if (uSER == null)
            {
                return HttpNotFound();
            }
            return View(uSER);
        }

        // POST: Admin/UZIVATEL/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            USER uSER = db.USER.Find(id);
            db.USER.Remove(uSER);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RKC_IS/RKC_IS/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    <link rel="apple-touch-icon" sizes="57x57" href="@Url.Content("~/Feature/Favicon/apple-icon-57x57.png")" />
    <link rel="apple-touch-icon" sizes="60x60" href="@Url.Content("~/Feature/Favicon/apple-icon-60x60.png")" />
    <link rel="apple-touch-icon" sizes="72x72" href="@Url.Content("~/Feature/Favicon/apple-icon-72x72.png")" />
    <link rel="apple-touch-icon" sizes="76x76" href="@Url.Content("~/Feature/Favicon/apple-icon-76x76.png")" />
    <link rel="apple-touch-icon" sizes="114x114" href="@Url.Content("~/Feature/Favicon/apple-icon-114x114.png")" />
    <link rel="apple-touch-icon" sizes="120x120" href="@Url.Content("~/Feature/Favicon/apple-icon-120x120.png")" />
    <link rel="apple-touch-icon" sizes="144x144" href="@Url.Content("~/Feature/Favicon/apple-icon-144x144.png")" />
    <link rel="apple-touch-icon" sizes="152x152" href="@Url.Content("~/Feature/Favicon/apple-icon-152x152.png")" />
    <link rel="apple-touch-icon" sizes="180x180" href="@Url.Content("~/Feature/Favicon/apple-icon-180x180.png")" />
    <link rel="icon" type="image/png" sizes="192x192" href="@Url.Content("~/Feature/Favicon/android-icon-192x192.png")" />
    <link rel="icon" type="image/png" sizes="32x32" href="@Url.Content("~/Feature/Favicon/favicon-32x32.png")" />
    <link rel="icon" type="image/png" sizes="96x96" href="@Url.Content("~/Feature/Favicon/favicon-96x96.png")" />
    <link rel="icon" type="image/png" sizes="16x16" href="@Url.Content("~/Feature/Favicon/favicon-16x16.png")" />
    <link rel="manifest" href="@Url.Content("~/Feature/Favicon/manifest.json")" />
    <meta name="msapplication-TileImage" href="@Url.Content("~/Feature/Favicon/ms-icon-144x144.png")" />

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        @*<div class="container">*@
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Administrace aplikace", "Index", "Home", new { area = "Admin" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Číselníky <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Číselník definice", "Index", "CISELNIK_DEFINICE", new { area = "Admin" }, null)</li>
                            <li>@Html.ActionLink("Číselník data", "Index", "CISELNIK_DATA", new { area = "Admin" }, null)</li>
                            @*<li><a href="#">Something else here</a></li>
                    <li role="separator" class="divider"></li>
                    <li class="dropdown-header">Nav header</li>
                    <li>@Html.ActionLink("Úvodní", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("UserIN", "Index", "Home", new { area = "UserIN" }, null)</li>*@
                        </ul>
                    </li>

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Uživatelé <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Seznam uživatelů", "Index", "UZIVATEL", new { area = "Admin" }, null)</li>
                            <li>@Html.ActionLink("Seznam rolí", "Index", "ROLEs", new { area = "Admin" }, null)</li>
                            @*<li><a href="#">Something else here</a></li>*@
                            <li role="separator" class="divider"></li>

                            <li class="dropdown-header">Správa IS</li>
                            <li>@Html.ActionLink("Založ účet", "Register", "Account", new { area = "" }, htmlAttributes: new { id = "registerLink" })</li>
                            <li>@Html.ActionLink("Založ roli", "Create", "ROLEs", new { area = "Admin" }, null)</li>
                            <li>@Html.ActionLink("Přiřadit roli uživateli", "Create", "USER_ROLE", new { area = "Admin" }, null)</li>

                        </ul>
                    </li>

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Správa databáze<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li class="dropdown-header">Tabulky</li>
                            <li>@Html.ActionLink("Záznam", "Index", "SY_TABULKA", new { area = "Admin" }, null)</li>
                            <li role="separator" class="divider"></li>
                            <li class="dropdown-header">Stavy</li>
                            <li>@Html.ActionLink("Záznam", "Index", "SY_STAV", new { area = "Admin" }, null)</li>
                            <li class="dropdown-header">Stavy-přechody</li>
                            <li>@Html.ActionLink("Záznam", "Index", "SY_PRECHOD", new { area = "Admin" }, null)</li>
                        </ul>
                    </li>
                </ul>



                <ul class="nav navbar-nav navbar-right">
                    @if (User.IsInRole("admin"))
                    {
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">IS <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                @*<li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li role="separator" class="divider"></li>*@
                                <li class="dropdown-header">Části</li>

                                <li>@Html.ActionLink("Výroba", "Index", "Home", new { area = "UserIN" }, null)</li>
                                <li>@Html.ActionLink("Bez přihlášení", "Index", "Home", new { area = "" }, null)</li>
                            </ul>
                        </li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        @*</div>*@
    </div>
    <div class="container body-content" id="dynamicContent">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Výrobní informační systém RKC</p>
        </footer>
    </div>

    @*@Scripts.Render("~/bundles/jquery")*@
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>