RKC_IS/RKC_IS/Areas/UserIN/Controllers/USER_GRUPAController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RKC_IS.DataAccess.Model.AutoMapping;

namespace RKC_IS.Areas.UserIN.Controllers
{
    public class USER_GRUPAController : Controller
    {
        private ConnectionMap_RKC_Database db = new ConnectionMap_RKC_Database();

        // GET: UserIN/USER_GRUPA
        public ActionResult Index()
        {
            var uSER_GRUPA = db.USER_GRUPA.Include(u => u.GRUPA).Include(u => u.USER);
            return View(uSER_GRUPA.ToList());
        }

        // GET: UserIN/USER_GRUPA/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            USER_GRUPA uSER_GRUPA = db.USER_GRUPA.Find(id);
            if (uSER_GRUPA == null)
            {
                return HttpNotFound();
            }
            return View(uSER_GRUPA);
        }

        // GET: UserIN/USER_GRUPA/Create
        public ActionResult Create()
        {
            ViewBag.ID_GRUPA = new SelectList(db.GRUPA, "ID", "Nazev");
            ViewBag.ID_USER = new SelectList(db.USER, "ID", "UserName");
            return View();
        }

        // POST: UserIN/USER_GRUPA/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,ID_USER,ID_GRUPA")] USER_GRUPA uSER_GRUPA)
        {
            if (ModelState.IsValid)
            {
                db.USER_GRUPA.Add(uSER_GRUPA);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ID_GRUPA = new SelectList(db.GRUPA, "ID", "Nazev", uSER_GRUPA.ID_GRUPA);
            ViewBag.ID_USER = new SelectList(db.USER, "ID", "UserName", uSER_GRUPA.ID_USER);
            return View(uSER_GRUPA);
        }

        // GET: UserIN/USER_GRUPA/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            USER_GRUPA uSER_GRUPA = db.USER_GRUPA.Find(id);
            if (uSER_GRUPA == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_GRUPA = new SelectList(db.GRUPA, "ID", "ZATG_TypGrupa", uSER_GRUPA.ID_GRUPA);
            ViewBag.ID_USER = new SelectList(db.USER, "ID", "ZAOR_organizace", uSER_GRUPA.ID_USER);
            return View(uSER_GRUPA);
        }

        // POST: UserIN/USER_GRUPA/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,ID_USER,ID_GRUPA")] USER_GRUPA uSER_GRUPA)
        {
            if (ModelState.IsValid)
            {
                db.Entry(uSER_GRUPA).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ID_GRUPA = new SelectList(db.GRUPA, "ID", "ZATG_TypGrupa", uSER_GRUPA.ID_GRUPA);
            ViewBag.ID_USER = new SelectList(db.USER, "ID", "ZAOR_organizace", uSER_GRUPA.ID_USER);
            return View(uSER_GRUPA);
        }

        // GET: UserIN/USER_GRUPA/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            USER_GRUPA uSER_GRUPA = db.USER_GRUPA.Find(id);
            if (uSER_GRUPA == null)
            {
                return HttpNotFound();
            }
            return View(uSER_GRUPA);
        }

        // POST: UserIN/USER_GRUPA/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            USER_GRUPA uSER_GRUPA = db.USER_GRUPA.Find(id);
            db.USER_GRUPA.Remove(uSER_GRUPA);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RKC_IS/RKC_IS/Areas/UserIN/Views/USER_GRUPA/Create.cshtml
@model RKC_IS.DataAccess.Model.AutoMapping.USER_GRUPA

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>USER_GRUPA</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ID_USER, "ID_USER", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_USER", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_USER, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_GRUPA, "ID_GRUPA", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_GRUPA", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_GRUPA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RKC_IS/RKC_IS/Areas/UserIN/Views/USER_GRUPA/Delete.cshtml
@model RKC_IS.DataAccess.Model.AutoMapping.USER_GRUPA

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>USER_GRUPA</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.GRUPA.ZATG_TypGrupa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GRUPA.ZATG_TypGrupa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.USER.ZAOR_organizace)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.USER.ZAOR_organizace)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

RKC_IS/RKC_IS/Areas/UserIN/Views/USER_GRUPA/Details.cshtml
@model RKC_IS.DataAccess.Model.AutoMapping.USER_GRUPA

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>USER_GRUPA</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.GRUPA.ZATG_TypGrupa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GRUPA.ZATG_TypGrupa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.USER.ZAOR_organizace)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.USER.ZAOR_organizace)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

RKC_IS/RKC_IS/Areas/UserIN/Views/USER_GRUPA/Edit.cshtml
@model RKC_IS.DataAccess.Model.AutoMapping.USER_GRUPA

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>USER_GRUPA</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.ID_USER, "ID_USER", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_USER", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_USER, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_GRUPA, "ID_GRUPA", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_GRUPA", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_GRUPA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RKC_IS/RKC_IS/Areas/UserIN/Views/USER_GRUPA/Index.cshtml
@model IEnumerable<RKC_IS.DataAccess.Model.AutoMapping.USER_GRUPA>

@{
    ViewBag.Title = "Seskupení - operátor";
}

    <h2>Seskupení - operáto</h2>

<p>
    @Html.ActionLink("ZALOŽIT", "Create","USER_GRUPA", new { @class="btn btn-default"})
</p>
<table class="table">
    <tr>
        <th>
            Název skupiny
        </th>
        <th>
            Zaměstnanec
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.GRUPA.Nazev)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.USER.Jmeno)
        @Html.DisplayFor(modelItem => item.USER.Prijmeni)
    </td>
    <td>
        @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
        @Html.ActionLink("Details", "Details", new { id = item.ID }) |
        @Html.ActionLink("Delete", "Delete", new { id = item.ID })
    </td>
</tr>
}

</table>