RKC_IS/RKC_IS/Areas/UserIN/Controllers/ZAKAZKAController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RKC_IS.DataAccess.Model.AutoMapping;
using PagedList;

namespace RKC_IS.Areas.UserIN.Controllers
{
    public class ZAKAZKAController : Controller
    {
        private ConnectionMap_RKC_Database db = new ConnectionMap_RKC_Database();

        // GET: UserIN/ZAKAZKA
        public ActionResult Index(string sortOrder, string currentFilter, string searchStringSTAV, int? page)
        {

            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "stav_desc" : "";
            ViewBag.DateSortParm = sortOrder == "stroj" ? "stroj_desc" : "stroj";

            if (searchStringSTAV != null)
            {
                page = 1;
            }
            else
            {
                searchStringSTAV = currentFilter;
            }

            ViewBag.CurrentFilter = searchStringSTAV;

            var zakazka_data = from s in db.ZAKAZKA.Include(z => z.SY_STAV).Include(z => z.STROJ)
                          select s;
            if (!String.IsNullOrEmpty(searchStringSTAV))
            {
                zakazka_data = zakazka_data.Where(s => s.CisloZakazka.Equals(searchStringSTAV)
                                       || s.SY_STAV.STAV.Equals(searchStringSTAV));
            }
            switch (sortOrder)
            {
                case "stav_desc":
                    zakazka_data = zakazka_data.OrderByDescending(s => s.SY_STAV.STAV);
                    break;
                case "stroj":
                    zakazka_data = zakazka_data.OrderBy(s => s.STROJ.Cislo);
                    break;
                case "stroj_desc":
                    zakazka_data = zakazka_data.OrderByDescending(s => s.STROJ.Cislo);
                    break;
                default:
                    zakazka_data = zakazka_data.OrderBy(s => s.SY_STAV.STAV);
                    break;
            }
            int pageSize = 20;
            int pageNumber = (page ?? 1);

            if (Request.IsAjaxRequest())
            {
                return PartialView(zakazka_data.ToPagedList(pageNumber, pageSize));
            }

            return View(zakazka_data.ToPagedList(pageNumber, pageSize));


            //var zAKAZKA = db.ZAKAZKA.Include(z => z.FORMA).Include(z => z.STROJ).Include(z => z.SY_STAV);
            //return View(zAKAZKA.ToList());
        }

        // GET: UserIN/ZAKAZKA/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ZAKAZKA zAKAZKA = db.ZAKAZKA.Find(id);
            if (zAKAZKA == null)
            {
                return HttpNotFound();
            }
            return View(zAKAZKA);
        }

        // GET: UserIN/ZAKAZKA/Create
        public ActionResult Create()
        {
            ViewBag.ID_FORMA = new SelectList(db.FORMA, "ID", "ZAFO_Forma");
            ViewBag.ID_STROJ = new SelectList(db.STROJ, "ID", "ZAOR_Organizace");
            ViewBag.STAV = new SelectList(db.SY_STAV, "ID", "TABULKA");
            return View();
        }

        // POST: UserIN/ZAKAZKA/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,ID_STROJ,ID_FORMA,CisloZakazka,Oznaceni,NazevProces,PlanovaneMnozstviNa,VyrobenoZahlaseno,ZbyvajiciMnozstvi,Hodnota,KonecnyT,DatumNasazeni,Pos,Nasobnost,CyklusCas,DobaPriprava,DobaVyroba,DobaPripravaVyroba,Priorita,PoznamkaNaVP,DelkaVymeny,CyklusCasReal,DatumUkonceni,ZahlaseneMnozstvi,ZaskladneneMnozstvi,C_USER,C_DATE,M_USER,M_DATE,STAV,STAV_NASLEDUJICI")] ZAKAZKA zAKAZKA)
        {
            if (ModelState.IsValid)
            {
                db.ZAKAZKA.Add(zAKAZKA);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ID_FORMA = new SelectList(db.FORMA, "ID", "ZAFO_Forma", zAKAZKA.ID_FORMA);
            ViewBag.ID_STROJ = new SelectList(db.STROJ, "ID", "ZAOR_Organizace", zAKAZKA.ID_STROJ);
            ViewBag.STAV = new SelectList(db.SY_STAV, "ID", "TABULKA", zAKAZKA.STAV);
            return View(zAKAZKA);
        }

        // GET: UserIN/ZAKAZKA/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ZAKAZKA zAKAZKA = db.ZAKAZKA.Find(id);
            if (zAKAZKA == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_FORMA = new SelectList(db.FORMA, "ID", "ZAFO_Forma", zAKAZKA.ID_FORMA);
            ViewBag.ID_STROJ = new SelectList(db.STROJ, "ID", "ZAOR_Organizace", zAKAZKA.ID_STROJ);
            ViewBag.STAV = new SelectList(db.SY_STAV, "ID", "TABULKA", zAKAZKA.STAV);
            return View(zAKAZKA);
        }

        // POST: UserIN/ZAKAZKA/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,ID_STROJ,ID_FORMA,CisloZakazka,Oznaceni,NazevProces,PlanovaneMnozstviNa,VyrobenoZahlaseno,ZbyvajiciMnozstvi,Hodnota,KonecnyT,DatumNasazeni,Pos,Nasobnost,CyklusCas,DobaPriprava,DobaVyroba,DobaPripravaVyroba,Priorita,PoznamkaNaVP,DelkaVymeny,CyklusCasReal,DatumUkonceni,ZahlaseneMnozstvi,ZaskladneneMnozstvi,C_USER,C_DATE,M_USER,M_DATE,STAV,STAV_NASLEDUJICI")] ZAKAZKA zAKAZKA)
        {
            if (ModelState.IsValid)
            {
                db.Entry(zAKAZKA).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ID_FORMA = new SelectList(db.FORMA, "ID", "ZAFO_Forma", zAKAZKA.ID_FORMA);
            ViewBag.ID_STROJ = new SelectList(db.STROJ, "ID", "ZAOR_Organizace", zAKAZKA.ID_STROJ);
            ViewBag.STAV = new SelectList(db.SY_STAV, "ID", "TABULKA", zAKAZKA.STAV);
            return View(zAKAZKA);
        }

        // GET: UserIN/ZAKAZKA/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ZAKAZKA zAKAZKA = db.ZAKAZKA.Find(id);
            if (zAKAZKA == null)
            {
                return HttpNotFound();
            }
            return View(zAKAZKA);
        }

        // POST: UserIN/ZAKAZKA/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            ZAKAZKA zAKAZKA = db.ZAKAZKA.Find(id);
            db.ZAKAZKA.Remove(zAKAZKA);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RKC_IS/RKC_IS/Areas/UserIN/Views/ZAKAZKA/Delete.cshtml
@model RKC_IS.DataAccess.Model.AutoMapping.ZAKAZKA

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/UserIN/Views/Shared/_LayoutLisovna.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ZAKAZKA</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CisloZakazka)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CisloZakazka)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Oznaceni)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Oznaceni)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NazevProces)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NazevProces)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PlanovaneMnozstviNa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PlanovaneMnozstviNa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VyrobenoZahlaseno)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VyrobenoZahlaseno)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ZbyvajiciMnozstvi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ZbyvajiciMnozstvi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hodnota)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hodnota)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.KonecnyT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KonecnyT)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DatumNasazeni)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DatumNasazeni)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pos)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pos)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nasobnost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nasobnost)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CyklusCas)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CyklusCas)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DobaPriprava)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DobaPriprava)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DobaVyroba)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DobaVyroba)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DobaPripravaVyroba)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DobaPripravaVyroba)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Priorita)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Priorita)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PoznamkaNaVP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PoznamkaNaVP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DelkaVymeny)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DelkaVymeny)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CyklusCasReal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CyklusCasReal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DatumUkonceni)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DatumUkonceni)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ZahlaseneMnozstvi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ZahlaseneMnozstvi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ZaskladneneMnozstvi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ZaskladneneMnozstvi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.C_USER)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.C_USER)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.C_DATE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.C_DATE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.M_USER)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.M_USER)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.M_DATE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.M_DATE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.STAV_NASLEDUJICI)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.STAV_NASLEDUJICI)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FORMA.ZAFO_Forma)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FORMA.ZAFO_Forma)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.STROJ.ZAOR_Organizace)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.STROJ.ZAOR_Organizace)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SY_STAV.TABULKA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SY_STAV.TABULKA)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

RKC_IS/RKC_IS/Areas/UserIN/Views/ZAKAZKA/Index.cshtml
@*@model IEnumerable<RKC_IS.DataAccess.Model.AutoMapping.ZAKAZKA>*@

@model PagedList.IPagedList<RKC_IS.DataAccess.Model.AutoMapping.ZAKAZKA>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Seznam zakázek";
    Layout = "~/Areas/UserIN/Views/Shared/_LayoutLisovna.cshtml";


}

<h2>Seznam zakázek</h2>

@using (Html.BeginForm("Index", "ZAKAZKA", FormMethod.Get))
{
    <p>
        Hledej podle STAV: @Html.TextBox("searchStringSTAV", ViewBag.CurrentFilter as string)
        <input type="submit" value="Hledat" />
    </p>
}

@*<p>
        @Html.ActionLink("Create New", "Create")
    </p>*@
<table class="table">
    <tr>
        <th>
            @*@Html.DisplayNameFor(model => model.SY_STAV.STAV)*@

            @*@Html.DisplayNameFor(model => model.DOMENA)*@

            @*@Html.ActionLink("DOMENA", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })*@
            @Ajax.ActionLink("STAV", "Index", "ZAKAZKA", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter }, new AjaxOptions() { InsertionMode = InsertionMode.Replace, UpdateTargetId = "dynamicContent" })

              @*@Ajax.ActionLink("DOMENA", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter }, new AjaxOptions() { InsertionMode = InsertionMode.Replace, UpdateTargetId = "dynamicContent" })*@

        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.SY_STAV.POPIS)*@
            POPIS

            @*@Html.DisplayNameFor(model => model.KOD)*@

            @*@Html.ActionLink("KOD", "Index", new { sortOrder = ViewBag.DateSortParm, currentFilter = ViewBag.CurrentFilter })*@

            @*@Ajax.ActionLink("POPIS", "Index", new { sortOrder = ViewBag.DateSortParm, currentFilter = ViewBag.CurrentFilter }, new AjaxOptions() { InsertionMode = InsertionMode.Replace, UpdateTargetId = "dynamicContent" })*@

        </th>
        <th>
            Číslo
        </th>
        <th>
            Označení
        </th>
        <th>
            Název procesu
        </th>
        <th>
            Plánované množství
        </th>
        <th>
            vyrobené-zahlášené množství
        </th>
        <th>
            zbývající množství
        </th>
        @*<th>
                @Html.DisplayNameFor(model => model.Hodnota)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.KonecnyT)
            </th>*@
        <th>
            čas nasazení
        </th>
        @*<th>
                @Html.DisplayNameFor(model => model.Pos)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nasobnost)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CyklusCas)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DobaPriprava)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DobaVyroba)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DobaPripravaVyroba)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Priorita)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PoznamkaNaVP)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DelkaVymeny)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CyklusCasReal)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DatumUkonceni)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ZahlaseneMnozstvi)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ZaskladneneMnozstvi)
            </th>*@
        @*<th>
                @Html.DisplayNameFor(model => model.C_USER)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.C_DATE)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.M_USER)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.M_DATE)
            </th>*@
        @*<th>
                @Html.DisplayNameFor(model => model.STAV_NASLEDUJICI)
            </th>*@
        <th>
            přidělená forma
        </th>
        <th>
           
            @Ajax.ActionLink("přidělený stroj", "Index", new { sortOrder = ViewBag.DateSortParm, currentFilter = ViewBag.CurrentFilter }, new AjaxOptions() { InsertionMode = InsertionMode.Replace, UpdateTargetId = "dynamicContent" })

        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.SY_STAV.STAV)

                @*@Html.ActionLink(item.SY_STAV.STAV, "Edit", new { id = item.ID })*@
                @*<a href="@Url.Action("Details", "ZAKAZKA", new { id = item.ID})">@Html.DisplayFor(modelItem => item.SY_STAV.STAV)</a>*@

                @*@Html.ActionLink("Edit", "Edit", new { id = item.ID })*@
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SY_STAV.POPIS)
            </td>
            <td>
                @*@Html.DisplayFor(modelItem => item.CisloZakazka)*@

                <a href="@Url.Action("Details", "ZAKAZKA", new { id = item.ID})">@Html.DisplayFor(modelItem => item.CisloZakazka)</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Oznaceni)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NazevProces)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PlanovaneMnozstviNa)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VyrobenoZahlaseno)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ZbyvajiciMnozstvi)
            </td>
            @*<td>
                    @Html.DisplayFor(modelItem => item.Hodnota)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.KonecnyT)
                </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.DatumNasazeni)
            </td>
            @*<td>
                    @Html.DisplayFor(modelItem => item.Pos)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nasobnost)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CyklusCas)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DobaPriprava)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DobaVyroba)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DobaPripravaVyroba)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Priorita)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PoznamkaNaVP)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DelkaVymeny)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CyklusCasReal)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DatumUkonceni)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ZahlaseneMnozstvi)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ZaskladneneMnozstvi)
                </td>*@
            @*<td>
                    @Html.DisplayFor(modelItem => item.C_USER)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.C_DATE)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.M_USER)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.M_DATE)
                </td>*@
            @*<td>
                    @Html.DisplayFor(modelItem => item.STAV_NASLEDUJICI)
                </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.FORMA.ZAFO_Forma)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.STROJ.Nazev)
                @Html.DisplayFor(modelItem => item.STROJ.Cislo)
            </td>

            @*<td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ID })
            </td>*@
        </tr>
    }

</table>


<br />
Stránka @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) z @Model.PageCount


@*@Html.PagedListPager(
        Model,
        page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }),
        PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions() { HttpMethod = "GET", UpdateTargetId = "dynamicContent" })
    )*@

@Html.PagedListPager(
    Model,
    page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }),
    PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions() { InsertionMode = InsertionMode.Replace, UpdateTargetId = "dynamicContent" })
)